### PR TITLE
enhancement: code for main menu

### PR DESCRIPTION
**Pull request by Kibent1234**
I am done revising @DianaCarino  code regarding her implementation of the program's main menu. I fixed the spaces and indentation as well. It shouldn't show any errors, but just to make sure, @Adz can you please review it?

### CODE REVIEW

**Comment by amzapanta** [comment]
Sure Kevin! I will review your code in just a moment.

**Comment by amzapanta** [comment]
Sure, Kevin! I will review your code in just a moment.

**Comment by amzapanta** [comment]
Sure, Kevin! I will review your code in just a moment.

**Comment by amzapanta** [comment]
Sure, Kevin! I will review your code in just a moment.

**Comment by amzapanta** [comment]
I have reviewed your code, and it seems pretty good! It followed our established coding standard, and there are no redundancies in the code. I'll mention our lead for him to accept your pull request. 

@SLU-Dominic I believe that Kevin's code is ready to be merged to the main branch! Your call.

**Comment by Kibent1234** [comment]
> I have reviewed your code, and it seems pretty good! It followed our established coding standard, and there are no redundancies in the code. I'll mention our lead for him to accept your pull request.
> 
> @SLU-Dominic I believe that Kevin's code is ready to be merged to the main branch! Your call.

Thanks, @amzapanta I appreciate your comment.

**Comment by amzapanta** [comment]
> > I have reviewed your code, and it seems pretty good! It followed our established coding standard, and there are no redundancies in the code. I'll mention our lead for him to accept your pull request.
> > @SLU-Dominic I believe that Kevin's code is ready to be merged to the main branch! Your call.
> 
> Thanks, @amzapanta I appreciate your comment.

No problem, Kevin!

**Comment by SLU-Dominic** [comment]
> I have reviewed your code, and it seems pretty good! It followed our established coding standard, and there are no redundancies in the code. I'll mention our lead for him to accept your pull request.
> 
> @SLU-Dominic I believe that Kevin's code is ready to be merged to the main branch! Your call.

I will now be merging this pull request. Thank you @amzapanta and @Kibent1234 !

**Pull request merged**
